# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Cache@2
  inputs:
    key: 'npm | $(Agent.OS) | package-lock.json'
    path: '/home/vsts/.npm'
    restoreKeys: 'npm | $(Agent.OS) | package-lock.json'
  displayName: Cache NPM packages
- task: Cache@2
  inputs:
    key: 'cypress | $(Agent.OS) | package-lock.json'
    path: '/home/vsts/.cache/Cypress'
    restoreKeys: 'cypress | $(Agent.OS) | package-lock.json'
  displayName: Cache Cypress binary

# Install Node dependencies


- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm install cypress
  displayName: 'install cypress'



- script: |
    npm run cy:verify
  displayName: 'verify cypress'

- script: |
    npm run cy:run
  displayName: 'open cypress'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
    mergeTestResults: true
    testRunTitle: 'Publish Test result'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Social27 cypress'
    publishLocation: 'Container'
  enabled: false
